# Generated by Django 3.0.8 on 2020-07-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('database', '0002_auto_20190129_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='constance',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='constance',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='constance',
            unique_together={('key', 'site')},
        ),
    ]
